### ISSUE TITLE
batch scripting xnat2bids

### ISSUE THREAD

**Issue by harrisonritz** [brown-bnc/xnat-tools#21]
currently the user needs to baby-sit the xnat2bids conversion because of password requirements. 
Would be great if the user could run xnat2bids as a batch script, without risking their password.
¯\_(ツ)_/¯

**Comment by mirestrepo** [comment]
@harrisonritz this is currently possible. The way to to it is to pass the flag `--password ${XNAT_PASSWORD}` You can define `XNAT_PASSWORD` as a variable in the current shell session or add it to your `~/.bashrc` file. You do so by adding a line to that file with 
`export XNAT_PASSWORD=<yourxnatpassword>`.
