### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/xnat-tools#4]
use dummy dataset and a guest account.

**Comment by mirestrepo** [comment]
Test have been added, but we should think of general strategy. It would be better if we have some tests data that can be made more public

**Comment by debyee** [comment]
have you considered using data from openfmri.org? [https://openfmri.org/ ]

Alternatively, you can probably tap into a study that has already been published from one of the groups here and use that, assuming the data are defaced and de-identified, something like this might be useful, depending on your objective.

**Comment by mirestrepo** [comment]
Those are all good ideas! A new test one is good because it offers the naming convention that people should use at the scanner, but we can also work on historic ones to provide more examples. Thanks for the ideas!
