### ISSUE TITLE
includesubj command line parameter does not match array name

### ISSUE THREAD

**Issue by broarr** [brown-bnc/xnat-tools#62]
https://github.com/brown-bnc/xnat-tools/blob/6b7da85b70c2b50c717469efe4b6dba06e5cd5a8/xnat_tools/bids_postprocess.py#L31-L36

I think the command line parameter should probably be `--includesubj` not `--includeseq`

**Comment by mirestrepo** [comment]
That would make more sense ;) - seems like I copy pasted from the other ones and made one inconsistent mess!
