### ISSUE TITLE
fix: bids_postprocess should only add IntendedFor field to boldSE/boldGRE fieldmap scans (not diffSE)

### ISSUE THREAD

**Issue by elizabethlorenc** [brown-bnc/xnat-tools#74]
if the diffSE fieldmaps are named _epi and automatically placed in the fmap folder, this bids-postprocess function also edits their jsons to say that they’re intended for the functional scans (even though they’re not). 

- bids validation passes if the IntendedFor field in the diffSE fieldmap is edited to point to the dwi scans, but for now people should just plan to do it manually, eg.: 
	"ses-01/dwi/sub-005_ses-01_acq-b1500_dir-ap_dwi.nii.gz",
	"ses-01/dwi/sub-005_ses-01_acq-b1500_dir-pa_dwi.nii.gz"

**Comment by debyee** [comment]
Good catch. Just putting a note that bids-postprocess function was originally written for and tested on T2* EPI bold runs, and has not been explicitly tested on dwi images (or other sorts of epi runs). 

@mirestrepo thoughts about this fix? Should be a somewhat straightforward fix in the code, though not sure if anyone is collecting diffusion data who is using the pipeline. Also, not sure if the code is open to suggestions from the broader community to suggest fixes, but could be worth considering.

**Comment by elizabethlorenc** [comment]
I wonder if we could more successfully automate these different cases by using the B0FieldIdentifier and B0FieldSource keys instead; seems worth looking into, at least.

https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#echo-planar-imaging-and-b0-mapping

**Comment by mirestrepo** [comment]
According to [this documentation](https://github.com/nipy/heudiconv/blob/e747f0595dd393384d65219f5137d42b2a5c8e73/docs/heuristics.rst) and the values in the ReproIn Heuristic [here](https://github.com/nipy/heudiconv/blob/e284072365e250d95de3f7ccc8e168298a403828/heudiconv/heuristics/reproin.py#L211) Heudiconv should already handle this if our `Shims` or `ImageVolume` match.... seems like our Shims don't match, why?
